"""Build-time leak detection: unresolved placeholders, staging URLs, debug flags, debug-signed APKs.

Complements ``network_security`` (which only inspects NSC) by sweeping the broader
decompiled tree for build-config slip-ups that indicate a debug/staging artifact
slipped into production.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from clawditor.config import RunContext
from clawditor.utils import logging as log

# Well-known Android debug-keystore SHA-1 (the cert auto-generated by the SDK
# for "Run as debug"). Same fingerprint across every IDE installation.
DEBUG_CERT_SHA1 = "61ed377e85d386a8dfee6b864bd85b0bfaa5af81"
DEBUG_CERT_SHA1_BYTES = bytes.fromhex(DEBUG_CERT_SHA1)
DEBUG_CN_MARKERS = ("CN=Android Debug", "CN = Android Debug", "Android Debug")

PLACEHOLDER_RX = re.compile(r"\$\{[A-Za-z_][A-Za-z0-9_]*\}")

# Hostnames whose left-most label is dev/staging/etc. Matches "staging-api.example.com",
# "dev.foo.in", "qa.bar.io", etc. We require the prefix to be followed by [.-] and then
# another labelled host ending in a TLD we care about.
STAGING_HOST_RX = re.compile(
    r"\b(?:https?://)?"
    r"(?P<host>(?:[a-z0-9-]+\.)*"
    r"(?:dev|staging|preprod|qa|test|internal|sandbox|uat)"
    r"[.\-][a-z0-9.\-]{3,80}"
    r"\.(?:com|in|io|net|app|co|tech|internal|local))\b",
    re.I,
)

# Hardcoded debug-mode constants. Smali compiles ``boolean DEBUG = true`` to
# ``.field public static final DEBUG:Z = true`` so we anchor on the ``:Z = true`` shape.
# Kotlin source (if jadx emits .java) compiles a bit differently — match both.
DEBUG_FLAG_RX = re.compile(
    r"\.field\s+(?:public|private|protected)?\s*(?:static\s+)?(?:final\s+)?"
    r"(?P<name>DEBUG|IS_DEBUG|DEBUG_MODE|ENABLE_LOGGING|LOG_ENABLED|LOGGING_ENABLED)"
    r":Z\s*=\s*true",
    re.I,
)
DEBUG_FLAG_JAVA_RX = re.compile(
    r"\b(?:DEBUG|IS_DEBUG|DEBUG_MODE|ENABLE_LOGGING|LOG_ENABLED|LOGGING_ENABLED)"
    r"\s*=\s*true\s*[;,)]",
    re.I,
)

# Skip vendor SDKs known to carry these tokens as harmless library artifacts.
VENDOR_HOST_SKIP = (
    "sentry.io", "okhttp", "retrofit", "junit", "mockito", "google", "amazonaws",
    "googleapis", "firebase", "facebook", "appsflyer", "branch.io", "crashlytics",
    "schema.org", "w3.org", "apache.org", "xmlpull.org", "stripe.com",
)

CAP = 200


def run(ctx: RunContext) -> dict:
    findings: dict = {
        "unresolved_placeholders": [],
        "staging_urls": [],
        "debug_flags": [],
        "debug_signed": None,
        "test_metadata": [],
    }

    root = ctx.decompiled_dir
    if not root.exists():
        log.warn("build_leaks: no decompiled dir; skipping")
        _write(ctx, findings)
        return findings

    _scan_placeholders(root, findings)
    _scan_staging_urls(root, findings)
    _scan_debug_flags(root, findings)
    _scan_test_metadata(ctx, findings)
    _scan_debug_signing(ctx, findings)

    # Dedupe list-shaped sections by (file, value/match) tuples.
    for k in ("unresolved_placeholders", "staging_urls", "debug_flags", "test_metadata"):
        findings[k] = _dedupe(findings[k])

    _write(ctx, findings)
    total = (
        len(findings["unresolved_placeholders"])
        + len(findings["staging_urls"])
        + len(findings["debug_flags"])
        + len(findings["test_metadata"])
        + (1 if findings["debug_signed"] else 0)
    )
    log.ok(f"build_leaks: {total} hit(s)")
    return findings


def _scan_placeholders(root: Path, findings: dict) -> None:
    targets = []
    res_root = root / "smali" / "resources"
    if res_root.exists():
        targets.extend(res_root.rglob("*.xml"))
    props_root = root / "smali" / "root"
    if props_root.exists():
        targets.extend(props_root.rglob("*.properties"))
    # Manifest sits at smali/AndroidManifest.xml — sweep too (dedup handled by NSC scanner
    # for NSC-specific entries downstream in findings.py).
    mf = root / "smali" / "AndroidManifest.xml"
    if mf.exists():
        targets.append(mf)

    for p in targets:
        if len(findings["unresolved_placeholders"]) >= CAP:
            break
        try:
            txt = p.read_text(errors="ignore")
        except Exception:
            continue
        for m in PLACEHOLDER_RX.finditer(txt):
            findings["unresolved_placeholders"].append({
                "file": _rel(p, root),
                "value": m.group(0),
            })
            if len(findings["unresolved_placeholders"]) >= CAP:
                break


def _scan_staging_urls(root: Path, findings: dict) -> None:
    # Resource XML strings are the most likely place an env URL ends up. Also
    # sweep smali (string constants compile into ``const-string`` lines).
    res_root = root / "smali" / "resources"
    targets = []
    if res_root.exists():
        targets.extend(res_root.rglob("*.xml"))
    smali_root = root / "smali"
    if smali_root.exists():
        targets.extend(smali_root.rglob("*.smali"))

    for p in targets:
        if len(findings["staging_urls"]) >= CAP:
            break
        try:
            txt = p.read_text(errors="ignore")
        except Exception:
            continue
        for m in STAGING_HOST_RX.finditer(txt):
            host = m.group("host").lower()
            if any(skip in host for skip in VENDOR_HOST_SKIP):
                continue
            # Crude false-positive trim: a string like "tests.test.example.com" is
            # fine but "junit.test.example" usually isn't from the app.
            findings["staging_urls"].append({
                "file": _rel(p, root),
                "value": m.group(0),
                "host": host,
            })
            if len(findings["staging_urls"]) >= CAP:
                break


def _scan_debug_flags(root: Path, findings: dict) -> None:
    smali_root = root / "smali"
    if not smali_root.exists():
        return
    for p in smali_root.rglob("*.smali"):
        if len(findings["debug_flags"]) >= CAP:
            break
        try:
            txt = p.read_text(errors="ignore")
        except Exception:
            continue
        for m in DEBUG_FLAG_RX.finditer(txt):
            findings["debug_flags"].append({
                "file": _rel(p, root),
                "match": m.group(0).strip(),
                "constant": m.group("name"),
            })
            if len(findings["debug_flags"]) >= CAP:
                break
    # jadx-emitted .java sources (if present)
    jadx_root = root / "jadx"
    if jadx_root.exists():
        for p in jadx_root.rglob("*.java"):
            if len(findings["debug_flags"]) >= CAP:
                break
            try:
                txt = p.read_text(errors="ignore")
            except Exception:
                continue
            for m in DEBUG_FLAG_JAVA_RX.finditer(txt):
                findings["debug_flags"].append({
                    "file": _rel(p, root),
                    "match": m.group(0).strip(),
                    "constant": m.group(0).split("=")[0].strip(),
                })
                if len(findings["debug_flags"]) >= CAP:
                    break


def _scan_test_metadata(ctx: RunContext, findings: dict) -> None:
    """Hunt for <meta-data> entries in manifest.json whose name screams 'test endpoint'."""
    mf_json = ctx.scan_dir / "manifest.json"
    if not mf_json.exists():
        return
    try:
        mf = json.loads(mf_json.read_text())
    except Exception:
        return
    md_entries = (mf.get("application") or {}).get("meta_data") or []
    # Match TEST / DEV / STAGING etc. as standalone tokens — be permissive
    # about underscores/dots/dashes around them since manifest names are e.g.
    # ``com.example.TEST_API_URL`` or ``com.foo.staging-base-url``.
    rx = re.compile(r"(?i)(?:^|[._\-])(test|dev|staging|preprod|qa|debug)(?:[._\-]|$)")
    for entry in md_entries:
        name = entry.get("name", "") or ""
        value = entry.get("value", "") or ""
        if rx.search(name) and (value.startswith("http://") or value.startswith("https://")):
            findings["test_metadata"].append({
                "name": name,
                "value": value[:200],
            })


def _scan_debug_signing(ctx: RunContext, findings: dict) -> None:
    sig_dir = ctx.decompiled_dir / "smali" / "signatures"
    if not sig_dir.exists():
        return
    for p in sig_dir.rglob("*"):
        if not p.is_file():
            continue
        try:
            raw = p.read_bytes()
        except Exception:
            continue
        # 1) SHA-1 fingerprint match — check both raw bytes and hex spelling
        # (some tools dump the fingerprint as a hex string in a side file).
        if DEBUG_CERT_SHA1_BYTES in raw or DEBUG_CERT_SHA1.lower().encode() in raw.lower():
            findings["debug_signed"] = {
                "file": _rel(p, ctx.decompiled_dir),
                "indicator": "android_debug_cert_sha1_match",
                "sha1": DEBUG_CERT_SHA1,
            }
            return
        # 2) Subject CN match — DER carries "Android Debug" as ASCII bytes.
        for marker in DEBUG_CN_MARKERS:
            if marker.encode() in raw:
                findings["debug_signed"] = {
                    "file": _rel(p, ctx.decompiled_dir),
                    "indicator": "android_debug_cn_match",
                    "marker": marker,
                }
                return


def _dedupe(items: list[dict]) -> list[dict]:
    seen = set()
    out = []
    for it in items:
        key = tuple(sorted(it.items()))
        if key in seen:
            continue
        seen.add(key)
        out.append(it)
    return out


def _rel(p: Path, root: Path) -> str:
    try:
        return str(p.relative_to(root))
    except ValueError:
        return str(p)


def _write(ctx: RunContext, findings: dict) -> None:
    (ctx.scan_dir / "build_leaks.json").write_text(json.dumps(findings, indent=2))


if __name__ == "__main__":  # pragma: no cover
    import sys
    out = Path(sys.argv[1])
    ctx = RunContext(package=None, apk_input=None, out_dir=out)
    run(ctx)
